### ISSUE TITLE
Request hooks can mutate request options

### ISSUE THREAD

**Issue by seanparmelee** [ExpediaGroup/service-client#31]
### Description
The `request` hook currently merges its results back into the `options` object that was passed into `request`: https://github.com/ExpediaGroup/service-client/blob/df0663054c538b708ef38bfba9ccd980f06ad2a9/lib/hooks.js#L101

Consumers probably aren't expecting their `options` object to be mutated.

### Steps to Reproduce
To reproduce, you'll need a service client plugin that has a `request` hook that returns a field that matches one of the options that was passed into the `request` call. Here's a simple, runnable example: https://repl.it/@seanparmelee/service-client-headers

**Expected behavior:**
The `headers` object that was passed in should not be mutated (i.e. should not contain `marker`)

**Actual behavior:**
The `headers` object was mutated; it contains the `marker` header that was generated by the plugin.

### Versions
2.0.0

**Comment by tuckbick** [comment]
We've logged this issue internally and will address it soon. Thanks!
